Cage.Web/Areas/member/Controllers/BaseMemberController.cs
using Cage.DAL.Db.Models;
using Cage.DAL.Db.Models.ViewModels.Member;
using Cage.DAL.Repository.Infrastructure;
using Cage.Web.Controllers.Base;
using Microsoft.AspNet.Identity;

namespace Cage.Web.Areas.member.Controllers
{
    public class BaseMemberController : BaseAttributesController
    {
        protected LayoutMemberViewModel LayoutMemberViewModel { get; private set; }
        protected ApplicationUser ReffererUser => UserManager.FindById(ApplicationUserDetails.ReferrerUserId);

        public BaseMemberController()
        {
        }

        public BaseMemberController(
            ICageUnitOfWorkAsync unitOfWork
            ) : base(unitOfWork)
        {
        }
    }
}

Cage.Web/Areas/member/Controllers/MemberController.cs
using Cage.Core;
using Cage.DAL.Db.Models.ViewModels.Member;
using Cage.Web.Core;
using System.Web.Mvc;

namespace Cage.Web.Areas.member.Controllers
{
    [AuthorizeRole(CageCode.RolesEnum.Member)]
    public class MemberController : BaseMemberController
    {
        // GET: member/Member
        public ActionResult Index()
        {
            var model = new LayoutMemberViewModel(ApplicationUser);
            //TODO:dashboard here
            return View(model);
        }
    }
}

Cage.Web/Controllers/Member/DashboardController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Cage.Core;
using Cage.DAL.Repository.Infrastructure;
using Cage.DAL.Service.Interfaces;
using Cage.DAL.Service.Manager;
using Cage.DAL.Db.Models;
using Cage.DAL.Db.Models.ViewModels.Member;

using System.Data.Entity.Validation;
using System.Collections.Generic;

namespace Cage.Web.Controllers.Member
{

    //public class DashboardController : Areas.member.Controllers.BaseMemberController
    public class DashboardController : Areas.member.Controllers.BaseMemberController
    {
        private readonly IUserHierarchySummalyViewService _userHierarchySummalyViewService;
        private readonly IUserPaymentSummalyService _userPaymentSummalyService;
        private readonly IUserShareHistorySummalyService _userShareHistorySummalyService;

        private readonly ProvideHelpManager _provideHelpManager;
        private readonly UserHierarchyMonthlyPairingManager _userHierarchyMonthlyPairingManager;

        public DashboardController(
            ICageUnitOfWorkAsync unitOfWork,
            IUserHierarchySummalyViewService userHierarchySummalyViewService,
            IUserPaymentSummalyService userPaymentSummalyService,
            IUserShareHistorySummalyService userShareHistorySummalyService,
            ProvideHelpManager provideHelpManager,
            UserHierarchyMonthlyPairingManager userHierarchyMonthlyPairingManager
            ) : base(unitOfWork)
        {
            _userHierarchySummalyViewService = userHierarchySummalyViewService;
            _userPaymentSummalyService = userPaymentSummalyService;
            _userShareHistorySummalyService = userShareHistorySummalyService;
            _provideHelpManager = provideHelpManager;
            _userHierarchyMonthlyPairingManager = userHierarchyMonthlyPairingManager;
        }

        // GET: Dashboard
        public async Task<ActionResult> Index()
        {
            var ups = await _userPaymentSummalyService.Queryable().Where(x => x.UserId == UserIdGuid).ToArrayAsync();

            var model = new DashboardViewModel(ApplicationUser)
            {
                ReffererUser = ReffererUser,
                AssistanceGivebackSummaryView = await GetAssistanceGivebackSummaly(ups),
                UserShareViewModel = await GetUserShareAsync(),
                PairingViewModel = new DashboardPairingViewModel
                {
                    CurrentPairing = await _userHierarchyMonthlyPairingManager.GetNextPairingValue(UserIdGuid)
                }
            };

            if (model.UserDetails.HasPledgePh)
                model.PhViewModel = await GetProvideHelpAsync();

            model.MembersSlotViewModel = new DashboardMembersSlotViewModel
            {
                User = model.User,
                UserDetails = model.UserDetails
            };

            //TODO:UserClass毎のハンドリング
            return View(model);
        }

        private async Task<DashboardAssistanceGivebackSummalyViewModel> GetAssistanceGivebackSummaly(UserPaymentSummaly[] userPaymentSummalies)
        {
            var sentAssistance = userPaymentSummalies.Where(x => x.Category == (int)CageCode.PaymentSummaryCategory.Upgrade);

            var pa = userPaymentSummalies
                .Where(x => x.UserId == UserIdGuid && x.Category == (int)CageCode.PaymentSummaryCategory.PA);
            var rgb = userPaymentSummalies.Where(x => x.Category == (int)CageCode.AssistanceGivebackPaymentType.RGB);

            var model = new DashboardAssistanceGivebackSummalyViewModel
            {
                SentAssistance = sentAssistance.Sum(x => x.Amount),
                ReceivedAssistance = pa.Any() ? pa.Sum(x => x.Amount) : 0,
                ReceivedGiveback = rgb.Any() ? rgb.Sum(x => x.Amount) : 0,
                UserHierarchySummalyViews = await _userHierarchySummalyViewService.Queryable().Where(x => x.UserId == UserIdGuid).ToListAsync()
            };
            return model;
        }

        private async Task<DashboardPhViewModel> GetProvideHelpAsync()
        {
            var effectiveUserProvideHelps = await _provideHelpManager.UserProvideHelpService.GetEffectiveUserProvideHelps(UserIdGuid);
            var userProvideHelps = effectiveUserProvideHelps as UserProvideHelp[] ?? effectiveUserProvideHelps.ToArray();
            if (!userProvideHelps.Any())
                return null;

            var totalPh =
                _provideHelpManager.UserProvideHelpService.GetEffectiveProvideHelpAmounts(userProvideHelps);
            var totalDivinded = userProvideHelps.Sum(x => x.Divinded);
            return new DashboardPhViewModel
            {
                TotalPh = totalPh,
                TotalDividend = totalDivinded
            };
        }

        private async Task<DashboardUserShareViewModel> GetUserShareAsync()
        {
            var model = new DashboardUserShareViewModel();
            var data = await _userShareHistorySummalyService.Queryable().Where(x => x.UserId == UserIdGuid).ToArrayAsync();
            if (!data.Any())
                return model;

            var pr = data.FirstOrDefault(x => x.Category == (int)CageCode.ShareCategory.PR);
            if (pr != null)
                model.PassportReferral = pr.Amount;

            var po = data.FirstOrDefault(x => x.Category == (int)CageCode.ShareCategory.PO);
            if (po != null)
                model.PassportOveriding = po.Amount;

            var phc = data.FirstOrDefault(x => x.Category == (int)CageCode.ShareCategory.PHC);
            if (phc != null)
                model.PhCapital = phc.Amount;

            var phd = data.FirstOrDefault(x => x.Category == (int)CageCode.ShareCategory.PHD);
            if (phd != null)
                model.PhDividend = phd.Amount;

            var phr = data.FirstOrDefault(x => x.Category == (int)CageCode.ShareCategory.PHR);
            if (phr != null)
                model.PhReferral = phr.Amount;

            var pho = data.FirstOrDefault(x => x.Category == (int)CageCode.ShareCategory.PHO);
            if (pho != null)
                model.PhOveriding = pho.Amount;

            var fp = data.FirstOrDefault(x => x.Category == (int)CageCode.ShareCategory.FP);
            if (fp != null)
                model.FlexPairing = fp.Amount;

            return model;
        }
    }
}

Cage.Web/Views/Shared/Member/_Layout.cshtml
@using Cage.Core
@model Cage.DAL.Db.Models.ViewModels.Member.LayoutMemberViewModel

@{
    var request = HttpContext.Current.Request;
    var context = request.RequestContext;
    var controller = context.RouteData.Values["Controller"].ToString().ToLower();
    var action = context.RouteData.Values["Action"].ToString().ToLower();

    ViewBag.Url = request.RawUrl;
}
<html lang="en">
<head>
    @Html.Partial("_HeadMetaPartial")
    @Html.Partial("_HeadMetaOpenGraphPartial")
    @Html.Partial("_HeadCssMainPartial")
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    @Html.Partial("_HeadIconsPartial")
    @Styles.Render("~/site.member/css")
    @RenderSection("css", required: false)
</head>

<body>
    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- SIDEBAR -->
        <div class="sidebar">
            <div class="brand">
                <a href="@Url.Action("Index","Home")"><img src="~/images/logo.png" alt="@($"{CageSettings.SiteName} Logo")" class="img-responsive logo"></a>
            </div>
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        <li class=""><a href="@Url.Action("Index", "Dashboard")"><i class="fa fa-list-alt"></i> <span>Dashboard</span></a></li>
                        <li><div class="sidebar-widget"><div class="widget-header"><h6>BANKING SERVICES</h6></div></div></li>
                        <li>
                            <a href="#subBank" data-toggle="collapse" class="collapsed">
                                <i class="fa fa-bank"></i> <span>Community Bank</span> <i class="icon-submenu lnr lnr-chevron-left"></i>
                            </a>
                            <div id="subBank" class="collapse ">
                                <ul class="nav">
                                    <li class="">@Html.ActionLink("Menu01", "Index", "Member")</li>
                                    <li class="">@Html.ActionLink("Menu02", "Index", "Member")</li>
                                </ul>
                            </div>
                        </li>
                        <li class=""><a href="@Url.Action("Index", "Member")"><i class="fa fa-btc"></i> <span>Menu03</span></a></li>
                        <li><div class="sidebar-widget"><div class="widget-header"><h6>NETWORK SERVICES</h6></div></div></li>
                        <li>
                            <a href="#subNtwk" data-toggle="collapse" class="collapsed">
                                <i class="fa fa-sitemap"></i> <span>Hierarchy</span> <i class="icon-submenu lnr lnr-chevron-left"></i>
                            </a>
                            <div id="subNtwk" class="collapse ">
                                <ul class="nav">
                                    <li class="">@Html.ActionLink("Menu03", "Index", "Member")</li>
                                    @*<li class="">@Html.ActionLink("Network Hierarchy", "Hierarchy", "Network")</li>
                                        <li class="">@Html.ActionLink("Referral Hierarchy", "Referral", "Network")</li>*@
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- END SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- NAVBAR -->
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-btn">
                        <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                    </div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu">
                            <span class="sr-only">Toggle Navigation</span>
                            <i class="fa fa-bars icon-nav"></i>
                        </button>
                    </div>
                    <div id="navbar-menu" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                    <i class="lnr lnr-alarm"></i>
                                    <span class="badge bg-danger">5</span>
                                </a>
                                <ul class="dropdown-menu notifications">
                                    <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
                                    <li><a href="#" class="more">See all notifications</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>Help</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Basic Use</a></li>
                                    <li><a href="#">Working With Data</a></li>
                                    <li><a href="#">Security</a></li>
                                    <li><a href="#">Troubleshooting</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="@Model.AvatarImageUrl" class="img-circle avatar" alt="Avatar"> <span>@Model.User.UserName</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
                                    <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                                    <li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                                    <li><a href="#" id="logout"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
                                </ul>
                                @using (Html.BeginForm("Logout", "Account", new { Area = "" }, FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                }
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- END NAVBAR -->
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <!-- CONTENTS -->
                    @RenderBody()
                    <!-- END CONTENTS -->
                </div>
            </div>
            <!-- END MAIN CONTENT -->
            <footer>
                <div class="container-fluid">
                    <p class="copyright">&copy; 2017. <a href="@CageSettings.SiteDomain">@CageSettings.SiteName</a></p>
                </div>
            </footer>
        </div>
        <!-- END MAIN -->
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->
    @Scripts.Render("~/jquery/js")
    @Scripts.Render("~/moment/js")
    @Scripts.Render("~/bootstrap/js")
    <script src="~/Scripts/jquery.slimscroll.js"></script>
    <script src="~/Scripts/jquery.easypiechart.js"></script>
    <script src="~/Scripts/klorofil.js"></script>
    @Scripts.Render("~/utils/js")
    @Scripts.Render("~/site.global/js")
    @RenderSection("scripts", required: false)
</body>
</html>