Cage.Web/Models/RoleManager/AssignUserRoleViewModel.cs
namespace Cage.Web.Models.RoleManager
{
    public class AssignUserRoleViewModel
    {
        public string Role { get; set; }
        public string Email { get; set; }
    }
}

Cage.Web/Models/RoleManager/CreateRoleViewModel.cs
namespace Cage.Web.Models.RoleManager
{
    public class CreateRoleViewModel
    {
        public string Role { get; set; }
    }
}

Cage.Web/Models/RoleManager/DeleteRoleViewModel.cs
namespace Cage.Web.Models.RoleManager
{
    public class DeleteRoleViewModel
    {
        public string Role { get; set; }
    }
}

Cage.Web/Models/RoleManager/UnassignUserRoleViewModel.cs
namespace Cage.Web.Models.RoleManager
{
    public class UnassignUserRoleViewModel
    {
        public string Role { get; set; }
        public string Email { get; set; }
    }
}

Cage.Web/Areas/Admin/Controllers/RoleManagerController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Cage.DAL.Db.Models;
using Cage.DAL.Repository.Infrastructure;
using Cage.Web.Controllers.Base;
using Cage.Web.Models.RoleManager;
using Identity;

namespace Cage.Web.Areas.Admin.Controllers
{
    public class RoleManagerController
        : BaseIdentityController
    {
        protected readonly ApplicationRoleManager RoleManager;


        public RoleManagerController(
            ICageUnitOfWorkAsync antUnitOfWorkAsync,
            ApplicationRoleManager roleManager) : base(antUnitOfWorkAsync)
        {
            RoleManager = roleManager;
        }


        public ActionResult Index()
        {
            return View();
        }



        #region Create Role
        public ActionResult CreateRole()
        {
            return View();
        }


        [ActionName("CreateRole"), HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateRole_POST(CreateRoleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (await RoleManager.RoleExistsAsync(model.Role))
            {
                ModelState.AddModelError("Role",
                    $"The role '{model.Role}' is already registered!");
            }
            else
            {
                await RoleManager.CreateAsync(new ApplicationRole(model.Role));
                TempData["Message"] = $"Role '{model.Role}' created successfully!";
                return RedirectToAction("Index");
            }

            return View(model);
        }
        #endregion Create Role



        #region Delete Role
        public ActionResult DeleteRole()
        {
            return View();
        }


        [ActionName("DeleteRole"), HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteRole_POST(DeleteRoleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var role = await RoleManager.FindByNameAsync(model.Role);

            if (role == null)
            {
                ModelState.AddModelError("Role",
                    $"The role '{model.Role}' does not exist!");
            }
            else
            {
                await RoleManager.DeleteAsync(role);
                TempData["Message"] = $"Role '{model.Role}' deleted successfully!";
                return RedirectToAction("Index");
            }

            return View(model);
        }
        #endregion Create Role



        #region Assign Role
        public ActionResult AssignRole()
        {
            return View();
        }


        [ActionName("AssignRole"), HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> AssignRole_POST(AssignUserRoleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await UserManager.FindByEmailAsync(model.Email);
            var role = await RoleManager.FindByNameAsync(model.Role);
            if (user == null)
            {
                ModelState.AddModelError("Email",
                    $"No user found with the email address '{model.Email}'!");
            }
            else if (role == null)
            {
                ModelState.AddModelError("Role",
                    $"The role '{model.Role}' does not exist!");
            }
            else
            {
                await UserManager.AddToRoleAsync(user.Id, role.Name);
                TempData["Message"] = $"User '{user.Email}' has been assigned to the role '{role.Name}'!";
                return RedirectToAction("Index");
            }

            return View(model);
        }
        #endregion Assign Role



        #region Unassign Role
        public ActionResult UnassignRole()
        {
            return View();
        }


        [ActionName("UnassignRole"), HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> UnassignRole_POST(UnassignUserRoleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await UserManager.FindByEmailAsync(model.Email);
            var role = await RoleManager.FindByNameAsync(model.Role);
            if (user == null)
            {
                ModelState.AddModelError("Email",
                    $"No user found with the email address '{model.Email}'!");
            }
            else if (role == null)
            {
                ModelState.AddModelError("Role",
                    $"The role '{model.Role}' does not exist!");
            }
            else if (!await UserManager.IsInRoleAsync(user.Id, role.Name))
            {
                ModelState.AddModelError("Role",
                    $"User '{user.Email}' has not been assigned the role '{role.Name}'!");
            }
            else
            {
                await UserManager.RemoveFromRoleAsync(user.Id, role.Name);
                TempData["Message"] =
                    $"User '{user.Email}' has been unassigned from the role '{role.Name}'!";
                return RedirectToAction("Index");
            }

            return View(model);
        }
        #endregion Assign Role
    }
}

Cage.Web/Areas/Admin/Views/RoleManager/AssignRole.cshtml
@model Cage.Web.Models.RoleManager.AssignUserRoleViewModel

    @{
        ViewBag.Title = "Assign Role";
    }

    <h2>@ViewBag.Title</h2>


    @using (Html.BeginForm("AssignRole", "RoleManager", FormMethod.Post,
                        new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()


        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.Role, new { @class = "col-xs-2 control-label" })
            <div class="col-xs-10">
                @Html.TextBoxFor(m => m.Role, new { @class = "form-control", autofocus = true })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-xs-2 control-label" })
            <div class="col-xs-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <input type="submit" class="btn btn-default" value="Assign" />
            </div>
        </div>
    }

Cage.Web/Areas/Admin/Views/RoleManager/CreateRole.cshtml
@model Cage.Web.Models.RoleManager.CreateRoleViewModel

    @{
        ViewBag.Title = "Create Role";
    }

    <h2>@ViewBag.Title</h2>


    @using (Html.BeginForm("CreateRole", "RoleManager", FormMethod.Post,
                        new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()


        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.Role, new { @class = "col-xs-2 control-label" })
            <div class="col-xs-10">
                @Html.TextBoxFor(m => m.Role, new { @class = "form-control", autofocus = true })
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <input type="submit" class="btn btn-default" value="Create" />
            </div>
        </div>
    }

Cage.Web/Areas/Admin/Views/RoleManager/DeleteRole.cshtml
@model Cage.Web.Models.RoleManager.DeleteRoleViewModel

    @{
        ViewBag.Title = "Delete Role";
    }

    <h2>@ViewBag.Title</h2>


    @using (Html.BeginForm("DeleteRole", "RoleManager", FormMethod.Post,
                        new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()


        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.Role, new { @class = "col-xs-2 control-label" })
            <div class="col-xs-10">
                @Html.TextBoxFor(m => m.Role, new { @class = "form-control", autofocus = true })
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </div>
    }

Cage.Web/Areas/Admin/Views/RoleManager/Index.cshtml
@{
    ViewBag.Title = "Simple Role Manager";
    string message = TempData["Message"] as string;
}

<h2>@ViewBag.Title</h2>

<p>
    Simple (crude!) utility for testing role creation and assignment.<br/>
    <em>This is not intended for production!</em>
</p>


@if (!String.IsNullOrWhiteSpace(message))
{
    <div class="well well-sm">
        <h3>Last Action</h3>
        <p>@message</p>
    </div>
}

<ul>
    <li>@Html.ActionLink("Create Role", "CreateRole", "RoleManager")</li>
    <li>@Html.ActionLink("Delete Role", "DeleteRole", "RoleManager")</li>
    <li>@Html.ActionLink("Assign Role", "AssignRole", "RoleManager")</li>
    <li>@Html.ActionLink("Unassign Role", "UnassignRole", "RoleManager")</li>
</ul>

Cage.Web/Areas/Admin/Views/RoleManager/UnassignRole.cshtml
@model Cage.Web.Models.RoleManager.UnassignUserRoleViewModel

    @{
        ViewBag.Title = "Unassign Role";
    }

    <h2>@ViewBag.Title</h2>


    @using (Html.BeginForm("UnassignRole", "RoleManager", FormMethod.Post,
                        new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()


        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.Role, new { @class = "col-xs-2 control-label" })
            <div class="col-xs-10">
                @Html.TextBoxFor(m => m.Role, new { @class = "form-control", autofocus = true })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-xs-2 control-label" })
            <div class="col-xs-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <input type="submit" class="btn btn-default" value="Unassign" />
            </div>
        </div>
    }